#!/usr/bin/python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Code extracted from Check MK...
#

import json
import os
import pprint
import subprocess
import tarfile
import time

package_parts = [
  ( "checks",        "Checks",                      "checks"),
  ( "agent_based",   "Agent based plugins (Checks, Inventory)", "agent_based"),
  ( "checkman",      "Checks' man pages",           "checks-man"),
  ( "agents",        "Agents",                      "agents"),
  ( "notifications", "Notification scripts",        "notifications"),
  ( "web",           "GUI extensions",              "web"),
  ( "doc",           "Documentation files",         "doc"),
]

pac_ext = ".mkp"

def files_in_dir(part, dir, prefix = ""):
    if not os.path.exists(dir):
        return []

    # Handle case where one part-dir lies below another
    taboo_dirs = [ d for p, t, d in package_parts if p != part ]
    if dir in taboo_dirs:
        return []

    result = []
    files = os.listdir(dir)
    for f in files:
        if f in [ '.', '..' ] or f.startswith('.') or f.endswith('~'):
            continue
        path = dir + "/" + f
        if os.path.isdir(path):
            result += files_in_dir(part, path, prefix + f + "/")
        else:
            result.append(prefix + f)
    result.sort()
    return result


class fake_file:
    def __init__(self, content):
        self.content = content
        self.pointer = 0

    def size(self):
        return len(self.content)

    def read(self, size):
        new_end = self.pointer + size
        data = self.content[self.pointer:new_end]
        self.pointer = new_end
        return data


#-----------------------------------------------------------------------

pacname = 'cmk-comet-p8xxx'
version = '2.0'

filelists = {}
package = {
    "title"                : "Comet P8xxx temperature sensor checks",
    "name"                 : pacname,
    "description"          : "monitoring Comet P8xxx temperature sensor using SNMP",
    "version"              : version,
    "version.packaged"     : '2.0.0p1',
    "version.min_required" : '2.0.0p1',
    "version.usable_until" : None,
    "author"               : "Vaclav Ovsik",
    "download_url"         : "https://github.com/zito/%s/" % pacname,
    "files"                : filelists
}

num_files = 0
for part, title, dir in package_parts:
    files = files_in_dir(part, dir)
    if files:
        filelists[part] = files
        num_files += len(files)
package["num_files"] = num_files


tarfilename = "%s-%s%s" % (pacname, version, pac_ext)

def create_info(filename, size):
    info = tarfile.TarInfo("info")
    info.mtime = time.time()
    info.uid = 0
    info.gid = 0
    info.size = size
    info.mode = 0o644
    info.type = tarfile.REGTYPE
    info.name = filename
    return info

tar = tarfile.open(tarfilename, "w:gz")
info_file = fake_file(pprint.pformat(package).encode())
info = create_info("info", info_file.size())
tar.addfile(info, info_file)
infojson_file = fake_file(json.dumps(package).encode())
infojson = create_info("info.json", infojson_file.size())
tar.addfile(infojson, infojson_file)

# Now pack the actual files into sub tars
for part, title, dir in package_parts:
    filenames = package["files"].get(part, [])
    if len(filenames) > 0:
        subtarname = part + ".tar"
        proc = subprocess.Popen(['tar', 'cf', '-', '--dereference', '--force-local',
                '-C', dir, *filenames],
                stdout=subprocess.PIPE)
        subdata = proc.stdout.read()
        info = create_info(subtarname, len(subdata))
        tar.addfile(info, fake_file(subdata))

tar.close()
